version: '3'

services:
  

  flask_app:
    container_name: flask_app
    restart: always
    build: 
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - docker/aws_env_creds
    volumes:
      - ./:/smart_retail
    working_dir: /smart_retail
    network_mode: "host"
    command: gunicorn -w 1 -b 0.0.0.0:5000 server_main:app
  

  flask_app_fridge_inference:
    container_name: flask_app_fridge_inference
    restart: always
    build: 
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    env_file:
      - docker/aws_env_creds
    volumes:
      - ./:/smart_retail
    working_dir: /smart_retail
    network_mode: "host"
    command: gunicorn -w 1 -b 0.0.0.0:6000 server_fridge_inference:app


  flask_app_cigar_inference:
    container_name: flask_app_cigar_inference
    restart: always
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    env_file:
      - docker/aws_env_creds
    volumes:
      - ./:/smart_retail
    working_dir: /smart_retail
    network_mode: "host"
    command: gunicorn -w 1 -b 0.0.0.0:7000 server_cigar_inference:app


  # flask_app_vaccine_inference:
  #   container_name: flask_app_vaccine_inference
  #   restart: always
  #   build:
  #     context: ./docker
  #     dockerfile: Dockerfile
  #   ports:
  #     - "7100:7100"
  #   env_file:
  #     - docker/aws_env_creds
  #   volumes:
  #     - ./:/smart_retail
  #   working_dir: /smart_retail
  #   network_mode: "host"
  #   command: gunicorn -w 2 -b 0.0.0.0:7100 server_vaccine_inference:app

  # nginx:
  #   container_name: nginx
  #   restart: always
  #   build: docker/nginx
  #   ports:
  #     - "5001:5001"
  #   depends_on:
  #     - flask_app
