version: '3'

services:   
  registry:
    image: registry
    ports: 
      - "50000:5000"    
    restart: always
    environment:
      - REGISTRY_STORAGE=s3
      - REGISTRY_STORAGE_S3_BUCKET=smart-retail-raspberry-docker
      - REGISTRY_STORAGE_S3_ACCESSKEY=${AWS_ACCESSKEY}
      - REGISTRY_STORAGE_S3_SECRETKEY=${AWS_SECRETKEY}
      - REGISTRY_STORAGE_S3_REGION=${AWS_REGION}     



